brick_types: [NO_BRICK, RED_BRICK, GREEN_BRICK, BLUE_BRICK, ORANGE_BRICK]

brick_ids:
  NO_BRICK: 0
  RED_BRICK: 1
  GREEN_BRICK: 2
  BLUE_BRICK: 3
  ORANGE_BRICK: 4

brick_rewards:
  NO_BRICK: 0
  RED_BRICK: 1
  GREEN_BRICK: 2
  BLUE_BRICK: 4
  ORANGE_BRICK: 6

brick_num_robot_requirements:
  NO_BRICK: 0
  RED_BRICK: 1
  GREEN_BRICK: 1
  BLUE_BRICK: 1
  ORANGE_BRICK: 2

brick_size_length_depth_height_cm:
  NO_BRICK: [0, 0, 0]
  RED_BRICK: [30, 20, 20]
  GREEN_BRICK: [60, 20, 20]
  BLUE_BRICK: [120, 20, 20]
  ORANGE_BRICK: [180, 20, 20]

#minimal distance of brick centers for concurrent building, set to e.g. 0 for deactivation, was 80
min_distance_concurrent_brick_placing_cm: 80

#whether to build entire layer first
entire_layer_first: false
minimize_total_time: false

#default values to be used when calling outside of ros service
time_budget_s: 2500

# first type of robot
num_robots: 3

builded_brick_ids: []
current_brick_ids: [-1, -1, -1]
times_finish_actual_s: [0, 0, 0]
battery_budgets_s: [0, 0, 0]
battery_recharge_s: [0, 0, 0]

brick_durations:
  NO_BRICK: 0
  RED_BRICK: 40
  GREEN_BRICK: 40
  BLUE_BRICK: 40
  ORANGE_BRICK: 40

brick_reservoir_time_from_wall_s:
  NO_BRICK: 0
  RED_BRICK: 10
  GREEN_BRICK: 10
  BLUE_BRICK: 10
  ORANGE_BRICK: 10

# second type of robot
num_robots2: 0

builded_brick_ids2: []
current_brick_ids2: []
times_finish_actual_s2: []
battery_budgets_s2: []
battery_recharge_s2: []

brick_durations2:
  NO_BRICK: 0
  RED_BRICK: 30
  GREEN_BRICK: 25
  BLUE_BRICK: 27
  ORANGE_BRICK: 50

brick_reservoir_time_from_wall_s2:
  NO_BRICK: 0
  RED_BRICK: 10
  GREEN_BRICK: 10
  BLUE_BRICK: 10
  ORANGE_BRICK: 10
#builded_brick_ids: [1, 2, 3]
#current_brick_ids: [-1, -1, 2]
#times_finish_actual_s: [20, 20, 20]

#builded_brick_ids: []
#current_brick_ids: [-1, -1, -1]
#times_finish_actual_s: [0, 0, 0]
#battery_budgets_s: [200, 200, 200]
#battery_recharge_s: [40, 40, 40]
